<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '60799491728b879e74601d83e38b2cad' => $vendorDir . '/illuminate/collections/helpers.php',
    '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => $vendorDir . '/symfony/polyfill-mbstring/bootstrap.php',
    'a4a119a56e50fbb293281d9a48007e0e' => $vendorDir . '/symfony/polyfill-php80/bootstrap.php',
    '72579e7bd17821bb1321b87411366eae' => $vendorDir . '/illuminate/support/helpers.php',
    '295ae5912a2716b9c41edbde326a26c7' => $baseDir . '/includes/Helpers/cbxmcratingreview-functions.php',
    '3db0f3bb7d52f16a00b4c939a99dfcc7' => $baseDir . '/includes/Helpers/cbxmcratingreview-tpl-loader.php',
    'ec4b387ee06631571a50211b4aa6b044' => $baseDir . '/includes/Helpers/CBXMCRatingReviewQuestionHelper.php',
    '9b1ae303aebb38c640a025ab79ef72e2' => $baseDir . '/includes/Helpers/CBXMCRatingReviewEmailFunctions.php',
);
