name: Deploy to WordPress.org

on:
  push:
    tags:
      - "*"

jobs:
  update-trunk:
    name: Update trunk in WordPress SVN
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install SVN
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion

      - name: WordPress Plugin Deploy (Trunk Only)
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          skip-existing-assets: true
          skip-tags: true
          generate-zip: false

        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

  tag-release:
    name: Tag SVN Release
    runs-on: ubuntu-latest
    needs: update-trunk

    steps:
      - uses: actions/checkout@v3

      - name: Install SVN
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion

      - name: Extract Plugin Version
        id: version
        run: |
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: WordPress Plugin Deploy (Tag Only)
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          skip-trunk: true
          skip-assets: true
          generate-zip: false
          tag: ${{ steps.version.outputs.version }}

        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

  github-release:
  name: Create GitHub Release
  runs-on: ubuntu-latest
  needs: [tag-release]

  steps:
    - uses: actions/checkout@v3

    - name: Extract Plugin Version
      id: version
      run: |
        echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Create ZIP
      run: |
        zip -r "${{ github.event.repository.name }}.zip" . -x ".git/*" ".github/*"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.version }}
        files: ${{ github.event.repository.name }}.zip

